# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/AppMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hj_interface.msg

class AppMsg(genpy.Message):
  _md5sum = "488a983cc55b1d58c4d05999345840f0"
  _type = "hj_interface/AppMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """AppData[]  appdata
AppData[]  metadata
uint64     timestamp
uint8      from 
uint8      to     
uint8      BLUETOOTH = 1
uint8      SHADOW  = 2
uint8      TOPIC = 3
uint8      CLOUD = 4 

================================================================================
MSG: hj_interface/AppData
string key
string payload
int8  res    	#response code

"""
  # Pseudo-constants
  BLUETOOTH = 1
  SHADOW = 2
  TOPIC = 3
  CLOUD = 4

  __slots__ = ['appdata','metadata','timestamp','from_','to']
  _slot_types = ['hj_interface/AppData[]','hj_interface/AppData[]','uint64','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       appdata,metadata,timestamp,from_,to

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AppMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.appdata is None:
        self.appdata = []
      if self.metadata is None:
        self.metadata = []
      if self.timestamp is None:
        self.timestamp = 0
      if self.from_ is None:
        self.from_ = 0
      if self.to is None:
        self.to = 0
    else:
      self.appdata = []
      self.metadata = []
      self.timestamp = 0
      self.from_ = 0
      self.to = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.appdata)
      buff.write(_struct_I.pack(length))
      for val1 in self.appdata:
        _x = val1.key
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.res
        buff.write(_get_struct_b().pack(_x))
      length = len(self.metadata)
      buff.write(_struct_I.pack(length))
      for val1 in self.metadata:
        _x = val1.key
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.res
        buff.write(_get_struct_b().pack(_x))
      _x = self
      buff.write(_get_struct_Q2B().pack(_x.timestamp, _x.from_, _x.to))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.appdata is None:
        self.appdata = None
      if self.metadata is None:
        self.metadata = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.appdata = []
      for i in range(0, length):
        val1 = hj_interface.msg.AppData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.key = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.key = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.payload = str[start:end]
        start = end
        end += 1
        (val1.res,) = _get_struct_b().unpack(str[start:end])
        self.appdata.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.metadata = []
      for i in range(0, length):
        val1 = hj_interface.msg.AppData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.key = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.key = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.payload = str[start:end]
        start = end
        end += 1
        (val1.res,) = _get_struct_b().unpack(str[start:end])
        self.metadata.append(val1)
      _x = self
      start = end
      end += 10
      (_x.timestamp, _x.from_, _x.to,) = _get_struct_Q2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.appdata)
      buff.write(_struct_I.pack(length))
      for val1 in self.appdata:
        _x = val1.key
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.res
        buff.write(_get_struct_b().pack(_x))
      length = len(self.metadata)
      buff.write(_struct_I.pack(length))
      for val1 in self.metadata:
        _x = val1.key
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.payload
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1.res
        buff.write(_get_struct_b().pack(_x))
      _x = self
      buff.write(_get_struct_Q2B().pack(_x.timestamp, _x.from_, _x.to))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.appdata is None:
        self.appdata = None
      if self.metadata is None:
        self.metadata = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.appdata = []
      for i in range(0, length):
        val1 = hj_interface.msg.AppData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.key = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.key = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.payload = str[start:end]
        start = end
        end += 1
        (val1.res,) = _get_struct_b().unpack(str[start:end])
        self.appdata.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.metadata = []
      for i in range(0, length):
        val1 = hj_interface.msg.AppData()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.key = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.key = str[start:end]
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.payload = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.payload = str[start:end]
        start = end
        end += 1
        (val1.res,) = _get_struct_b().unpack(str[start:end])
        self.metadata.append(val1)
      _x = self
      start = end
      end += 10
      (_x.timestamp, _x.from_, _x.to,) = _get_struct_Q2B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Q2B = None
def _get_struct_Q2B():
    global _struct_Q2B
    if _struct_Q2B is None:
        _struct_Q2B = struct.Struct("<Q2B")
    return _struct_Q2B
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
