# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/CleanRecord.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CleanRecord(genpy.Message):
  _md5sum = "6b54b5e0d54e66ca8836b8669debbb38"
  _type = "hj_interface/CleanRecord"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 clean_speed             # 清洁速度 单位：m/s
float32 surface_clean_area      # 清洁水面面积 单位：m2
float32 bottom_clean_area       # 清洁池底面积
float32 wall_clean_area         # 清洁池壁面积
float32 pool_area               # 泳池面积
float32 pool_volume             # 泳池体积
string map_line_file_path       # 地图轨迹文件路径

## not to be reported for the time being
#uint8 avoid_obstacles          # 避障次数
#int32 get_out_time             # 脱困时长 单位：秒
#uint8 get_out_failed           # 脱困失败次数
#uint8 get_out_success          # 脱困成功次数
#float32 supple_clean_area      # 补扫面积 """
  __slots__ = ['clean_speed','surface_clean_area','bottom_clean_area','wall_clean_area','pool_area','pool_volume','map_line_file_path']
  _slot_types = ['float32','float32','float32','float32','float32','float32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       clean_speed,surface_clean_area,bottom_clean_area,wall_clean_area,pool_area,pool_volume,map_line_file_path

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CleanRecord, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.clean_speed is None:
        self.clean_speed = 0.
      if self.surface_clean_area is None:
        self.surface_clean_area = 0.
      if self.bottom_clean_area is None:
        self.bottom_clean_area = 0.
      if self.wall_clean_area is None:
        self.wall_clean_area = 0.
      if self.pool_area is None:
        self.pool_area = 0.
      if self.pool_volume is None:
        self.pool_volume = 0.
      if self.map_line_file_path is None:
        self.map_line_file_path = ''
    else:
      self.clean_speed = 0.
      self.surface_clean_area = 0.
      self.bottom_clean_area = 0.
      self.wall_clean_area = 0.
      self.pool_area = 0.
      self.pool_volume = 0.
      self.map_line_file_path = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.clean_speed, _x.surface_clean_area, _x.bottom_clean_area, _x.wall_clean_area, _x.pool_area, _x.pool_volume))
      _x = self.map_line_file_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.clean_speed, _x.surface_clean_area, _x.bottom_clean_area, _x.wall_clean_area, _x.pool_area, _x.pool_volume,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_line_file_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_line_file_path = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.clean_speed, _x.surface_clean_area, _x.bottom_clean_area, _x.wall_clean_area, _x.pool_area, _x.pool_volume))
      _x = self.map_line_file_path
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.clean_speed, _x.surface_clean_area, _x.bottom_clean_area, _x.wall_clean_area, _x.pool_area, _x.pool_volume,) = _get_struct_6f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_line_file_path = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_line_file_path = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
