# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/Imu.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class Imu(genpy.Message):
  _md5sum = "c3f4a9e0bb13a9f736bd9f1ddae855bc"
  _type = "hj_interface/Imu"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time custom_time
int16 roll
int16 pitch
int16 yaw
int16 gyro_x
int16 gyro_y
int16 gyro_z
int16 accel_x
int16 accel_y
int16 accel_z
uint64 index
"""
  __slots__ = ['custom_time','roll','pitch','yaw','gyro_x','gyro_y','gyro_z','accel_x','accel_y','accel_z','index']
  _slot_types = ['time','int16','int16','int16','int16','int16','int16','int16','int16','int16','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       custom_time,roll,pitch,yaw,gyro_x,gyro_y,gyro_z,accel_x,accel_y,accel_z,index

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      if self.roll is None:
        self.roll = 0
      if self.pitch is None:
        self.pitch = 0
      if self.yaw is None:
        self.yaw = 0
      if self.gyro_x is None:
        self.gyro_x = 0
      if self.gyro_y is None:
        self.gyro_y = 0
      if self.gyro_z is None:
        self.gyro_z = 0
      if self.accel_x is None:
        self.accel_x = 0
      if self.accel_y is None:
        self.accel_y = 0
      if self.accel_z is None:
        self.accel_z = 0
      if self.index is None:
        self.index = 0
    else:
      self.custom_time = genpy.Time()
      self.roll = 0
      self.pitch = 0
      self.yaw = 0
      self.gyro_x = 0
      self.gyro_y = 0
      self.gyro_z = 0
      self.accel_x = 0
      self.accel_y = 0
      self.accel_z = 0
      self.index = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I9hQ().pack(_x.custom_time.secs, _x.custom_time.nsecs, _x.roll, _x.pitch, _x.yaw, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.accel_x, _x.accel_y, _x.accel_z, _x.index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 34
      (_x.custom_time.secs, _x.custom_time.nsecs, _x.roll, _x.pitch, _x.yaw, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.accel_x, _x.accel_y, _x.accel_z, _x.index,) = _get_struct_2I9hQ().unpack(str[start:end])
      self.custom_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I9hQ().pack(_x.custom_time.secs, _x.custom_time.nsecs, _x.roll, _x.pitch, _x.yaw, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.accel_x, _x.accel_y, _x.accel_z, _x.index))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 34
      (_x.custom_time.secs, _x.custom_time.nsecs, _x.roll, _x.pitch, _x.yaw, _x.gyro_x, _x.gyro_y, _x.gyro_z, _x.accel_x, _x.accel_y, _x.accel_z, _x.index,) = _get_struct_2I9hQ().unpack(str[start:end])
      self.custom_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I9hQ = None
def _get_struct_2I9hQ():
    global _struct_2I9hQ
    if _struct_2I9hQ is None:
        _struct_2I9hQ = struct.Struct("<2I9hQ")
    return _struct_2I9hQ
