// Generated by gencpp from file hj_interface/SlamNaviWorkResultRequest.msg
// DO NOT EDIT!


#ifndef HJ_INTERFACE_MESSAGE_SLAMNAVIWORKRESULTREQUEST_H
#define HJ_INTERFACE_MESSAGE_SLAMNAVIWORKRESULTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hj_interface/CleanRecord.h>

namespace hj_interface
{
template <class ContainerAllocator>
struct SlamNaviWorkResultRequest_
{
  typedef SlamNaviWorkResultRequest_<ContainerAllocator> Type;

  SlamNaviWorkResultRequest_()
    : action_cmd(0)
    , action_result(0)
    , CleanRecord()  {
    }
  SlamNaviWorkResultRequest_(const ContainerAllocator& _alloc)
    : action_cmd(0)
    , action_result(0)
    , CleanRecord(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _action_cmd_type;
  _action_cmd_type action_cmd;

   typedef uint8_t _action_result_type;
  _action_result_type action_result;

   typedef  ::hj_interface::CleanRecord_<ContainerAllocator>  _CleanRecord_type;
  _CleanRecord_type CleanRecord;





  typedef boost::shared_ptr< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SlamNaviWorkResultRequest_

typedef ::hj_interface::SlamNaviWorkResultRequest_<std::allocator<void> > SlamNaviWorkResultRequest;

typedef boost::shared_ptr< ::hj_interface::SlamNaviWorkResultRequest > SlamNaviWorkResultRequestPtr;
typedef boost::shared_ptr< ::hj_interface::SlamNaviWorkResultRequest const> SlamNaviWorkResultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator1> & lhs, const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action_cmd == rhs.action_cmd &&
    lhs.action_result == rhs.action_result &&
    lhs.CleanRecord == rhs.CleanRecord;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator1> & lhs, const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hj_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c9ebd4d7ac2622dfb79b45c1cf84115";
  }

  static const char* value(const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c9ebd4d7ac2622dULL;
  static const uint64_t static_value2 = 0xfb79b45c1cf84115ULL;
};

template<class ContainerAllocator>
struct DataType< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hj_interface/SlamNaviWorkResultRequest";
  }

  static const char* value(const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 action_cmd            # 1: 建图 2: 重定位 \n"
"                            # 11: 清扫 \n"
"                            # 16：navi建图/重定位延边 17：navi极限延边\n"
"                            # 18: 姿态调整\n"
"                            # 21: 召回 22: 回充\n"
"\n"
"uint8 action_result         # 1: slam建图成功 2: slam建图失败 \n"
"                            # 11: slam定位成功 12: slam定位失败 \n"
"                            # 21: navi清扫成功 22: navi清扫失败\n"
"                            # 26：建图/重定位延边停止 27：极限延边停止\n"
"                            # 31：navi姿态调整成功 32：navi姿态调整失败\n"
"                            # 41: navi召回成功 42: navi召回失败 \n"
"                            # 51: navi回充成功 52: navi回充失败 \n"
"CleanRecord CleanRecord     # 清扫记录\n"
"\n"
"\n"
"================================================================================\n"
"MSG: hj_interface/CleanRecord\n"
"## 清洁日志消息\n"
"float32 clean_speed             # 清洁速度 单位：m/s\n"
"float32 surface_clean_area      # 清洁水面面积 单位：m2\n"
"float32 bottom_clean_area       # 清洁池底面积\n"
"float32 wall_clean_area         # 清洁池壁面积\n"
"float32 water_line_clean_area   # 清洁水线面积\n"
"float32 pool_area               # 泳池面积\n"
"float32 pool_volume             # 泳池体积\n"
"float32 pool_depth              # 泳池最大深度\n"
"float32 pool_little_depth       # 泳池最小深度\n"
"int32   pool_shape              # 泳池形状\n"
"string  map_line_file_path      # 地图轨迹文件路径\n"
"int32   avoidObstaclesCount     # 避障次数\n"
"int32   getOutCount             # 脱困次数\n"
"int32   multiple_bottom         # 多层池底 1-单层 2-多层\n"
"\n"
"#### 以下用于埋点的消息\n"
"## 清洁事件消息- 与清洁日志消息高度重叠\n"
"\n"
"## 清洁不同区域共同信息\n"
"float32 clean_area             # 清扫面积\n"
"int32 trapped_count            # 被困次数\n"
"\n"
"## 水面清洁信息\n"
"int32 edge_time                # 延边时长\n"
"\n"
"## 池底清洁信息 - 无多余信息\n"
"\n"
"## 池壁清洁信息 - 无多余信息\n"
"\n"
"## 水线清洁信息 - 无多余信息\n"
"\n"
"## 多平台清洁信息\n"
"int32 fall_count               # 跌落次数\n"
"int32 avoid_fall               # 防跌落次数\n"
"int32[] clean_time               # 清洁时长\n"
"float32[] deepth_list          # 深度列表\n"
;
  }

  static const char* value(const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_cmd);
      stream.next(m.action_result);
      stream.next(m.CleanRecord);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SlamNaviWorkResultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hj_interface::SlamNaviWorkResultRequest_<ContainerAllocator>& v)
  {
    s << indent << "action_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_cmd);
    s << indent << "action_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action_result);
    s << indent << "CleanRecord: ";
    s << std::endl;
    Printer< ::hj_interface::CleanRecord_<ContainerAllocator> >::stream(s, indent + "  ", v.CleanRecord);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HJ_INTERFACE_MESSAGE_SLAMNAVIWORKRESULTREQUEST_H
