# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/FileUpload.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FileUpload(genpy.Message):
  _md5sum = "38c9514b3de5bb0395288defad45567f"
  _type = "hj_interface/FileUpload"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8  MAP  = 0
uint8  TRACE = 1
uint8  CLEANRESULT = 2
uint8  DEVICELOG = 3
uint8  BURYPOINT = 4
uint8  type
bool  deleteOnSuccess
string filePath
"""
  # Pseudo-constants
  MAP = 0
  TRACE = 1
  CLEANRESULT = 2
  DEVICELOG = 3
  BURYPOINT = 4

  __slots__ = ['type','deleteOnSuccess','filePath']
  _slot_types = ['uint8','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,deleteOnSuccess,filePath

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FileUpload, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.deleteOnSuccess is None:
        self.deleteOnSuccess = False
      if self.filePath is None:
        self.filePath = ''
    else:
      self.type = 0
      self.deleteOnSuccess = False
      self.filePath = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.type, _x.deleteOnSuccess))
      _x = self.filePath
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.type, _x.deleteOnSuccess,) = _get_struct_2B().unpack(str[start:end])
      self.deleteOnSuccess = bool(self.deleteOnSuccess)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.filePath = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.filePath = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B().pack(_x.type, _x.deleteOnSuccess))
      _x = self.filePath
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.type, _x.deleteOnSuccess,) = _get_struct_2B().unpack(str[start:end])
      self.deleteOnSuccess = bool(self.deleteOnSuccess)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.filePath = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.filePath = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
