# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/ElecMotorCur.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ElecMotorCur(genpy.Message):
  _md5sum = "ea5172ded50d937bdf2d9c842bf711d0"
  _type = "hj_interface/ElecMotorCur"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time custom_time
uint16 motor_l
uint16 motor_r
uint16 pump_l
uint16 pump_r
uint16 turn
uint16 dirtybox
uint16 flipcover
uint16 airbag
"""
  __slots__ = ['custom_time','motor_l','motor_r','pump_l','pump_r','turn','dirtybox','flipcover','airbag']
  _slot_types = ['time','uint16','uint16','uint16','uint16','uint16','uint16','uint16','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       custom_time,motor_l,motor_r,pump_l,pump_r,turn,dirtybox,flipcover,airbag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ElecMotorCur, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      if self.motor_l is None:
        self.motor_l = 0
      if self.motor_r is None:
        self.motor_r = 0
      if self.pump_l is None:
        self.pump_l = 0
      if self.pump_r is None:
        self.pump_r = 0
      if self.turn is None:
        self.turn = 0
      if self.dirtybox is None:
        self.dirtybox = 0
      if self.flipcover is None:
        self.flipcover = 0
      if self.airbag is None:
        self.airbag = 0
    else:
      self.custom_time = genpy.Time()
      self.motor_l = 0
      self.motor_r = 0
      self.pump_l = 0
      self.pump_r = 0
      self.turn = 0
      self.dirtybox = 0
      self.flipcover = 0
      self.airbag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I8H().pack(_x.custom_time.secs, _x.custom_time.nsecs, _x.motor_l, _x.motor_r, _x.pump_l, _x.pump_r, _x.turn, _x.dirtybox, _x.flipcover, _x.airbag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.custom_time.secs, _x.custom_time.nsecs, _x.motor_l, _x.motor_r, _x.pump_l, _x.pump_r, _x.turn, _x.dirtybox, _x.flipcover, _x.airbag,) = _get_struct_2I8H().unpack(str[start:end])
      self.custom_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I8H().pack(_x.custom_time.secs, _x.custom_time.nsecs, _x.motor_l, _x.motor_r, _x.pump_l, _x.pump_r, _x.turn, _x.dirtybox, _x.flipcover, _x.airbag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.custom_time is None:
        self.custom_time = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.custom_time.secs, _x.custom_time.nsecs, _x.motor_l, _x.motor_r, _x.pump_l, _x.pump_r, _x.turn, _x.dirtybox, _x.flipcover, _x.airbag,) = _get_struct_2I8H().unpack(str[start:end])
      self.custom_time.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I8H = None
def _get_struct_2I8H():
    global _struct_2I8H
    if _struct_2I8H is None:
        _struct_2I8H = struct.Struct("<2I8H")
    return _struct_2I8H
