# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hj_interface/UploadIot.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class UploadIot(genpy.Message):
  _md5sum = "bdbbf36d412f43a626768d6f424a1d73"
  _type = "hj_interface/UploadIot"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time   timestamp   #!< 时间戳, 单位us
uint32 code_val    #!< 错误码, enum值

uint8  status        #!< 错误程度, enum值
uint8 FAILED  = 1    # 致命错误
uint8 ERROR   = 2    # 一般错误
uint8 WARNING = 3    # 警告
uint8 NORMAL  = 4    # 正常"""
  # Pseudo-constants
  FAILED = 1
  ERROR = 2
  WARNING = 3
  NORMAL = 4

  __slots__ = ['timestamp','code_val','status']
  _slot_types = ['time','uint32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       timestamp,code_val,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UploadIot, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.code_val is None:
        self.code_val = 0
      if self.status is None:
        self.status = 0
    else:
      self.timestamp = genpy.Time()
      self.code_val = 0
      self.status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3IB().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.code_val, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.code_val, _x.status,) = _get_struct_3IB().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3IB().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.code_val, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.code_val, _x.status,) = _get_struct_3IB().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3IB = None
def _get_struct_3IB():
    global _struct_3IB
    if _struct_3IB is None:
        _struct_3IB = struct.Struct("<3IB")
    return _struct_3IB
