uint16 bridge_circuit_vol   # bridge circuit voltage,mV
uint16 charger_ch_vol       # charger channel voltage,mV
uint16 bridge_circuit_cur   # bridge circuit current,mA
uint16 charger_ch_cur       # charger channel current,mA
uint16 bridge_circuit_temp  # bridge circuit temperature,°C
uint16 coil_temp            # coil temperature,°C
uint16 charging_cradle_vol  # charging cradle voltage,mV
uint16 charging_cradle_cur  # charging cradle current,mA
uint16 charging_cradle_temp  # charging cradle temperature,°C
uint8  charging_cradle_status 